import type { RewardMetadata } from '../gameplay/economy';
import type { ItemId } from '../gameplay/equipment';
import type { EnemyId } from '../gameplay/encounter';
import type { GrassPatch, GrassVariant } from './grass';
import type { LightingRecipe } from './lighting';
import type { LocalLightRole } from './local-lighting';
import type { Traversal } from '../gameplay/movement';
import type { WaterDefinition } from './water';
import type { PortalDefinition } from '../rendering/portal';
import type { EncounterLayout, Gate, Point, Spawn } from '../gameplay/area.ts';
export type RainShelter = { center: Point; restoredOnly?: boolean } & ({ radius: number; halfSize?: never; yaw?: never } | { halfSize: Point; yaw?: number; radius?: never });
export type EnvironmentLighting = { sky: string; horizon: string; ground: string; sunColor: string; sunIntensity: number; intensity: number; rotation: number };
export type ProbeLighting = { position: [number, number, number]; size: [number, number, number]; resolution: [number, number, number]; intensity: number; bounces: number };
export type AssetRef = { url: string } | { libraryId: string };
export type GroundLayer = 'earth' | 'litter' | 'rocky-soil';
export type GroundPatch = { center: Point; radius: number; color: string; strength: number; wetness?: number; layer?: GroundLayer };
export type GroundPath = { points: Point[]; width: number; strength: number };
export type VegetationProfile = 'soft' | 'shrub';
export type Primitive = { kind: 'box' | 'cylinder' | 'pebble' | 'tent' | 'headstone'; size: number[]; color: string; doubleSided?: boolean; surface?: 'woodland' | 'stone'; patches?: GroundPatch[]; paths?: GroundPath[] };
export type Placement = {
  id: string; visibility?: 'lighting-only'; position: [number, number, number]; yaw: number; scale: [number, number, number];
  asset?: AssetRef; primitive?: Primitive; height?: number; foliage?: boolean; vegetation?: VegetationProfile | false; decoration?: boolean; terrain?: boolean;
  harvest?: { kind: 'tree' | 'stone' | 'iron'; radius?: number; level?: number; baseYield?: number; contacts?: number };
  castShadow: boolean; receiveShadow: boolean; fallback?: AssetRef;
};
export type Region = { id: string; center: Point; radius: number; role: 'combat' | 'arrival' | 'route' };
export type LightingGrade = { shadows: string; highlights: string; strength: number };
export type AreaLighting = { background: string; fogNear: number; fogFar: number; ambient: { sky: string; ground: string; intensity: number }; sun: { color: string; intensity: number; position: [number, number, number]; shadowExtent: number }; environment?: EnvironmentLighting; probes?: ProbeLighting; saturation?: number; grade?: LightingGrade };
export type Shop = { id: string; prop: string; position: Point; merchant: { model: string; position: Point; yaw: number; height: number } };
export type Chest = RewardMetadata & { id: string; prop: string; position: Point; scrolls: number; potions?: number; equipment?: ItemId[] };
export type Campfire = { id: string; name: string; position: Point; arrival: Spawn; heals?: boolean };
export type AreaDefinition = {
  version: 1; id: string; name: string; ambience?: 'woodland' | 'quiet'; level?: number; shop?: Shop; legacy?: boolean; terminal?: boolean; chests?: Chest[]; enemyEquipment?: Partial<Record<EnemyId,ItemId[]>>; kind?: 'safe' | 'encounter'; campfires?: Campfire[]; portalArrival?: Spawn;
  smithing?: { prop: string; position: Point };
  shelter?: { position: Point; yaw: number; stash: Point };
  envelope: { width: number; depth: number; apron: number; yaw: number; reference: { width: number; height: number; zoom: number }; screen: [number, number] };
  layout: EncounterLayout; traversal?: Traversal; seed: number; props: Placement[];
  scatter: { id: string; count: number; radius: [number, number]; primitive: Primitive; harvest?: Placement['harvest']; excludedIds: string[] }[];
  grass?: GrassPatch[]; grassVariants?: GrassVariant[]; grassLimit?: number;
  reserved: Region[]; gates: Gate[]; lighting: LightingRecipe;
  effects: { weather?: { kind: 'rain'; shelters?: RainShelter[] }; portals?: PortalDefinition[]; water: WaterDefinition[]; fires: { id: string; position: Point; asset: AssetRef; height: number; emitterHeight?: number; intensity?: number; role?: LocalLightRole; color?: string; distance?: number; shadow?: boolean }[] };
  views: { id: string; target: [number, number, number] }[];
  inspection?: { position: Point };
};

export type ResolvedAreaDefinition = Omit<AreaDefinition, 'lighting'> & { lighting: AreaLighting };
