import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { cli, parseArgs, root, isMain } from '../lib/cli.mjs';
const presets = ['baseline','sharpness-0','sharpness-1','foliage-motion','reactive-coverage','mip-minus-half','mip-minus-one'];
if (isMain(import.meta.url)) await cli(async () => {
  const args = parseArgs(process.argv.slice(2), { '--directory':'value' });
  if (args['--help']) { console.log('Usage: node scripts/levels/fsr-report.mjs [--directory DIR]\nBuild the private synchronized review page after all seven captures.'); return; }
  const directory = resolve(args['--directory'] ?? resolve(root,'.local/level-design/fsr-comparison'));
  const manifests = await Promise.all(presets.map(async preset => JSON.parse(await readFile(resolve(directory,preset,'manifest.json'),'utf8'))));
  const baseline = manifests[0];
  for (const take of manifests) if (take.sourceSignature !== baseline.sourceSignature || take.contentHash !== baseline.contentHash || JSON.stringify(take.trace) !== JSON.stringify(baseline.trace)) throw new Error('Reports require matched takes.');
  const data = manifests.map(take => ({preset:take.preset,sharpness:take.settings.sharpness,mipBias:take.pipeline.materialMipBias,inputs:take.inputStats}));
  const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Lantern · FSR comparisons</title>
<style>body{margin:0;background:#14181d;color:#ece9df;font:16px system-ui}header,main{padding:24px;max-width:1800px;margin:auto}h1{font-size:26px}p{max-width:950px;line-height:1.5;color:#c9c8bf}button,select{font:inherit;padding:8px;background:#29333b;color:#eee;border:1px solid #66717b;border-radius:5px}button[aria-pressed=true]{background:#826638}nav,.playback{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.lanes{display:grid;grid-template-columns:repeat(var(--lanes),minmax(0,1fr));gap:14px}article{min-width:0;background:#20262d;border-radius:8px;padding:12px}article h2{font-size:18px;margin:0 0 8px}video,img{display:block;width:100%;background:#090b0c}img{cursor:zoom-in}small{display:block;margin:8px 0;color:#b9b7ab}a{color:#edcd89}.playback input{flex:1;min-width:180px}dialog{max-width:95vw;max-height:95vh;background:#15191e;color:#eee;border:1px solid #778;padding:12px}dialog img{width:auto;max-width:none}dialog .scroll{overflow:auto;max-height:85vh;max-width:90vw}dialog::backdrop{background:#000c}@media(max-width:900px){.lanes{grid-template-columns:1fr}}</style>
<header><h1>Lantern · FSR image-quality comparisons</h1><p>Quality · 1920 × 1080 output · 1280 × 720 scene · current lighting and cinematic depth of field. Each variant changes one variable. All takes use the same private wind fixture on authored tree meshes; current Clearing placements do not enable this general foliage-wind helper. Click a PNG to inspect its original pixels. Videos show eight simulation seconds; recording speed does not establish game performance.</p>
<nav id="groups"></nav><div class="playback"><button id="play">Play together</button><button id="restart">Restart</button><input id="scrub" type="range" min="0" max="7.99" value="0" step="0.016667" aria-label="Video position"><output id="time">0.00 s</output><select id="rate" aria-label="Playback speed"><option value="1">1×</option><option value="0.5">½ speed</option></select></div>
<label>Lossless still <select id="still"><option value="still">Settled start</option><option value="frame-240">During movement</option><option value="frame-330">Weapon attack</option><option value="frame-479">After stopping</option></select></label>
<p id="description"></p></header><main><div id="lanes" class="lanes"></div><p>Compare texture clarity against sparkle, edge halos, trails and disappearing detail. These candidates are unadopted; the shipping sharpening remains 0.50. Velocity previews exaggerate signed motion around neutral gray; reactive previews show mask coverage in white.</p><a href="baseline/manifest.json">Capture metadata</a> · <a href="observations.txt">Review observations</a></main>
<dialog id="zoom"><button id="close">Close</button><div class="scroll"><img id="full" alt="Original PNG pixels"></div></dialog>
<script>
const takes=${JSON.stringify(data).replaceAll('<','\\u003c')};
const groups=[{name:'Sharpening',presets:['sharpness-0','baseline','sharpness-1'],labels:['0.00','0.50 · current','1.00'],description:'Look at blade edges, canopy detail and ground texture. Sharpening can increase contrast without recovering missing detail.'},{name:'Foliage motion',presets:['baseline','foliage-motion'],labels:['Current motion vectors','Previous wind deformation'],description:'Watch swaying foliage with the camera still, then moving and stopping. Current visible wind motion is identical.'},{name:'Reactive coverage',presets:['baseline','reactive-coverage'],labels:['Current color-difference mask','Added alpha coverage · capped 0.9'],description:'Watch fire, smoke, drifting particles and water. Less trailing can trade off against more visible noise.'},{name:'Mip bias',presets:['baseline','mip-minus-half','mip-minus-one'],labels:['−0.585 · current','−1.085','−1.585'],description:'Compare bark, rock and soil at rest and while the camera moves. Extra detail may introduce shimmer.'}];
let current=0,videos=[],playing=false;const byId=id=>document.getElementById(id);
function pause(){playing=false;videos.forEach(v=>v.pause());byId('play').textContent='Play together';}
function seek(t){pause();videos.forEach(v=>{if(v.readyState)v.currentTime=Math.min(t,v.duration||8)});byId('scrub').value=t;byId('time').textContent=t.toFixed(2)+' s';}
function stills(){const name=byId('still').value;document.querySelectorAll('[data-still]').forEach(img=>img.src=img.dataset.preset+'/'+name+'.png');document.querySelectorAll('[data-crop]').forEach(img=>img.src=img.dataset.preset+'/'+name+'-'+img.dataset.crop+'.png');}
function show(index){pause();current=index;const group=groups[index];byId('description').textContent=group.description;byId('lanes').style.setProperty('--lanes',group.presets.length);byId('lanes').innerHTML=group.presets.map((preset,i)=>'<article><h2>'+group.labels[i]+'</h2><video muted playsinline preload="auto" src="'+preset+'/clip.webm"></video><small>Full scene · click still for original pixels</small><img data-still data-preset="'+preset+'" alt="'+group.labels[i]+' full scene"><small>Foliage · identical crop</small><img data-crop="foliage" data-preset="'+preset+'" alt="Foliage crop"><small>Weapon · identical crop</small><img data-crop="weapon" data-preset="'+preset+'" alt="Weapon crop"><small>Ground · identical crop</small><img data-crop="ground" data-preset="'+preset+'" alt="Ground crop"><details><summary>Temporal inputs</summary><img src="'+preset+'/velocity-before.png" alt="Signed velocity visualization"><img src="'+preset+'/reactive-before.png" alt="Reactive mask"></details><small><a href="'+preset+'/clip.webm">Video file</a> · <a href="'+preset+'/manifest.json">Metadata</a></small></article>').join('');videos=[...document.querySelectorAll('video')];videos.forEach(v=>{v.playbackRate=Number(byId('rate').value);v.addEventListener('ended',()=>seek(0));v.addEventListener('error',()=>{pause();byId('description').textContent='Video could not load. Open the individual file or lossless PNGs.'})});stills();byId('scrub').value=0;document.querySelectorAll('nav button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===current)));}
byId('groups').innerHTML=groups.map(g=>'<button>'+g.name+'</button>').join('');[...byId('groups').children].forEach((button,i)=>button.onclick=()=>show(i));
byId('play').onclick=async()=>{if(playing){pause();return;}try{const t=Number(byId('scrub').value);videos.forEach(v=>{v.currentTime=t});await Promise.all(videos.map(v=>v.play()));playing=true;byId('play').textContent='Pause together';}catch(error){pause();byId('description').textContent=String(error)}};
byId('restart').onclick=()=>seek(0);byId('scrub').oninput=event=>seek(Number(event.target.value));byId('rate').onchange=()=>videos.forEach(v=>v.playbackRate=Number(byId('rate').value));byId('still').onchange=stills;
byId('lanes').onclick=event=>{if(event.target.tagName==='IMG'){byId('full').src=event.target.src;byId('zoom').showModal()}};byId('close').onclick=()=>byId('zoom').close();
function tick(){if(playing&&videos.length){const t=videos[0].currentTime;byId('scrub').value=t;byId('time').textContent=t.toFixed(2)+' s';videos.slice(1).forEach(v=>{if(Math.abs(v.currentTime-t)>.04)v.currentTime=t})}requestAnimationFrame(tick)}show(0);tick();
</script></html>`;
  await writeFile(resolve(directory,'index.html'),html); console.log(`Review page: ${resolve(directory,'index.html')}`);
});
